name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: docker pull mcr.microsoft.com/windows/servercore:ltsc2019
      - run: docker tag mcr.microsoft.com/windows/servercore:ltsc2019 microsoft/windowsservercore
      - run: docker build -t nativebuildimage -f .\Dockerfile.windows .
      - run: docker run --name binaries -e DOCKER_GITCOMMIT=$env:GITHUB_SHA -e VERSION=2.10.13.1 -e PRODUCT=Shmoby nativebuildimage hack\make.ps1 -Binary
      - run: docker cp binaries:C:\gopath\src\github.com\docker\docker\bundles\dockerd.exe dockerd.exe
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: "*.exe"
      - name: publish to gh-releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
